// Mocks generated by Mockito 5.4.4 from annotations
// in mvvm_project/test/features/home/data/repository/repositoryHome_impl.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hive/hive.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mvvm_project/core/common/data/model/model_cache.dart' as _i4;
import 'package:mvvm_project/core/common/network/network_info.dart' as _i7;
import 'package:mvvm_project/features/features_home/data/data_source/local_data_source.dart'
    as _i8;
import 'package:mvvm_project/features/features_home/data/data_source/remote_data_source_home.dart'
    as _i5;
import 'package:mvvm_project/features/features_home/data/responeses/model_user.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeModelUserResponse_0 extends _i1.SmartFake
    implements _i2.ModelUserResponse {
  _FakeModelUserResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_1<E> extends _i1.SmartFake implements _i3.Box<E> {
  _FakeBox_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModel_Cache_2 extends _i1.SmartFake implements _i4.Model_Cache {
  _FakeModel_Cache_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSourceHome].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSourceHome extends _i1.Mock
    implements _i5.RemoteDataSourceHome {
  MockRemoteDataSourceHome() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ModelUserResponse> getUser(
    String? page,
    String? per_page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [
            page,
            per_page,
          ],
        ),
        returnValue:
            _i6.Future<_i2.ModelUserResponse>.value(_FakeModelUserResponse_0(
          this,
          Invocation.method(
            #getUser,
            [
              page,
              per_page,
            ],
          ),
        )),
      ) as _i6.Future<_i2.ModelUserResponse>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i8.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Box<dynamic>> Openbox() => (super.noSuchMethod(
        Invocation.method(
          #Openbox,
          [],
        ),
        returnValue: _i6.Future<_i3.Box<dynamic>>.value(_FakeBox_1<dynamic>(
          this,
          Invocation.method(
            #Openbox,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Box<dynamic>>);

  @override
  _i6.Future<_i4.Model_Cache> getCache() => (super.noSuchMethod(
        Invocation.method(
          #getCache,
          [],
        ),
        returnValue: _i6.Future<_i4.Model_Cache>.value(_FakeModel_Cache_2(
          this,
          Invocation.method(
            #getCache,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Model_Cache>);

  @override
  _i6.Future<void> AddCache(_i4.Model_Cache? modelcache) => (super.noSuchMethod(
        Invocation.method(
          #AddCache,
          [modelcache],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteLocal(dynamic tittle) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocal,
          [tittle],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
